spring.application.name=SpringSeEx

spring.security.user.name=""
spring.security.user.password=""

spring.datasource.url=jdbc:mysql://localhost:3306/ankit1
spring.datasource.username=root
spring.datasource.password=719438
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret.key=dGVzdFNlY3JldEtleVdpdGhTdWZmaWNpZW50TGVuZ3Ro